CREATE TABLE users(id int primary key, telegram_user_id int, telegram_username varchar(250));
CREATE SEQUENCE users_id_seq;
alter table users alter column id set default nextval('users_id_seq');
ALTER TABLE IF EXISTS users ADD COLUMN telegram_first_name varchar(250);
ALTER TABLE IF EXISTS users ADD COLUMN telegram_last_name varchar(250);
ALTER TABLE users ADD COLUMN verified boolean;
ALTER TABLE users ADD COLUMN login_token char(30);
ALTER TABLE users ADD COLUMN login_token_expire_at timestamptz;
CREATE TABLE telegram_updates(id bigint primary key);
alter table telegram_updates rename to processed_telegram_updates;